import streamlit as st
import json
import pandas as pd
import io
import markdown
import uuid
import base64
import zlib
import requests
import re
from weasyprint import HTML
from websockets.sync.client import connect
from websockets.exceptions import ConnectionClosed

st.set_page_config(page_title="Baseera AI OSINT", layout="wide")
st.title("Baseera AI: Due Diligence Agent")

# Initialize Session State Variables
if "live_claims" not in st.session_state:
    st.session_state.live_claims = []
if "thread_id" not in st.session_state:
    st.session_state.thread_id = str(uuid.uuid4())
if "workflow_status" not in st.session_state:
    st.session_state.workflow_status = "idle"
if "draft_plan" not in st.session_state:
    st.session_state.draft_plan = {}
if "final_report_md" not in st.session_state:
    st.session_state.final_report_md = ""



def inject_mermaid_svgs(markdown_text: str) -> str:
    pattern = r"```mermaid\n(.*?)\n```"
    
    def replace_with_svg(match):
        mermaid_code = match.group(1)
        # Compress and encode for the Kroki API
        compressed = zlib.compress(mermaid_code.encode('utf-8'), 9)
        encoded = base64.urlsafe_b64encode(compressed).decode('ascii')
        
        response = requests.get(f"https://kroki.io/mermaid/svg/{encoded}")
        if response.status_code == 200:
            # WeasyPrint natively renders this inline SVG
            return f'<div style="text-align: center; margin: 30px 0;">\n{response.text}\n</div>'
        return "*(Diagram generation failed)*"

    return re.sub(pattern, replace_with_svg, markdown_text, flags=re.DOTALL)

def generate_pdf(markdown_text: str, company_name: str) -> bytes:
    html_content = markdown.markdown(markdown_text, extensions=['tables', 'fenced_code'])
    styled_html = f"""
    <html>
        <head>
            <style>
                body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; margin: 40px; }}
                h1 {{ color: #2c3e50; border-bottom: 2px solid #34495e; padding-bottom: 10px; }}
                h2 {{ color: #34495e; margin-top: 30px; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
                th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; color: #333; }}
                
                /* Add this image constraint rule */
                img {{ max-width: 550px; height: auto; display: block; margin: 30px auto; }}
                
                .footer {{ text-align: center; margin-top: 50px; font-size: 12px; color: #7f8c8d; }}
            </style>
        </head>
        <body>
            <h1>Baseera OSINT Due Diligence Report</h1>
            <h3>Target: {company_name}</h3>
            <hr>
            {html_content}
            <div class="footer">Generated by Baseera AI System</div>
        </body>
    </html>
    """
    pdf_buffer = io.BytesIO()
    HTML(string=styled_html).write_pdf(pdf_buffer)
    return pdf_buffer.getvalue()

# Sidebar inputs mapping directly to BaseeraState
with st.sidebar:
    st.header("Research Parameters")
    company_name = st.text_input("Target Company", value="Saudi Telecom Company (STC)")
    research_goal = st.text_area("Research Goal", value="diversification strategy")
    if st.button("Execute Due Diligence", type="primary"):
        st.session_state.workflow_status = "running_planner"
        st.session_state.thread_id = str(uuid.uuid4()) # Reset for new run

# Phase 1: Run Planner
if st.session_state.workflow_status == "running_planner":
    with st.spinner("Generating MECE Issue Tree..."):
        with connect("ws://localhost:8000/ws/diligence") as websocket:
            websocket.send(json.dumps({
                "action": "start",
                "thread_id": st.session_state.thread_id,
                "company_name": company_name,
                "research_goal": research_goal
            }))
            
            while True:
                try:
                    data = json.loads(websocket.recv())
                    if data.get("status") == "paused_for_review":
                        st.session_state.draft_plan = data.get("plan", {})
                        st.session_state.workflow_status = "awaiting_approval"
                        st.rerun()
                except ConnectionClosed:
                    break

# Phase 2: Human Review
if st.session_state.workflow_status == "awaiting_approval":
    st.warning("Review and edit the proposed issue tree before committing to web research.")
    edited_plan_str = st.text_area("Research Plan (JSON)", value=json.dumps(st.session_state.draft_plan, indent=2), height=300)
    
    if st.button("Approve & Execute Search", type="primary"):
        st.session_state.draft_plan = json.loads(edited_plan_str)
        st.session_state.workflow_status = "running_research"
        st.rerun()

# Phase 3: Resume Search & Synthesis
if st.session_state.workflow_status == "running_research":
    
    st.subheader("Live Fact-Checking & Synthesis")
    
    # 1. An empty placeholder to hold the live updating table above the logs
    claims_placeholder = st.empty()
    
    # 2. A status container to show a spinning progress bar and live node logs
    with st.status(" Launching Parallel OSINT Agents...", expanded=True) as status_box:
        
        with connect("ws://localhost:8000/ws/diligence") as websocket:
            websocket.send(json.dumps({
                "action": "resume",
                "thread_id": st.session_state.thread_id,
                "edited_plan": st.session_state.draft_plan
            }))
            
            while True:
                try:
                    msg = websocket.recv()
                    data = json.loads(msg)
                    
                    if data.get("status") == "error":
                        status_box.update(label="Execution Failed", state="error")
                        st.error(f"Backend error: {data.get('error')}")
                        st.session_state.workflow_status = "awaiting_approval"
                        break

                    node_name = data.get("node")
                    state_update = data.get("state_update", {})
                    
                    # Log the active node inside the status box
                    if node_name and node_name != "__start__":
                        st.write(f"🔄 **{node_name}** is processing...")
                    
                    # 3. Live-render claims as subgraphs complete
                    if isinstance(state_update, dict) and "all_verified_claims" in state_update:
                        new_claims = state_update["all_verified_claims"]
                        if new_claims:
                            st.session_state.live_claims.extend(new_claims)
                            
                            # Flatten for DataFrame rendering
                            flat_claims = []
                            for c in st.session_state.live_claims:
                                flat_claims.append({
                                    "Domain": c.get("domain", "N/A"),
                                    "Claim": c.get("claim_data", {}).get("claim", ""),
                                    "Status": c.get("verification_status", ""),
                                    "Source": c.get("claim_data", {}).get("source", "")
                                })
                            
                            # Instantly update the table placeholder
                            claims_placeholder.dataframe(pd.DataFrame(flat_claims), use_container_width=True)
                    
                    # 4. Finalize and close the status box
                    if isinstance(state_update, dict) and "final_report" in state_update:
                        st.session_state.final_report_md = state_update["final_report"]
                        status_box.update(label="✅ OSINT Research & Synthesis Complete!", state="complete", expanded=False)
                        st.session_state.workflow_status = "complete"
                        st.rerun()

                except ConnectionClosed:
                    break

# Phase 4: Final Output rendering from Session State
if st.session_state.workflow_status == "complete":
    st.success("Report Generation Complete")
    st.markdown(st.session_state.final_report_md)
    pdf_bytes = generate_pdf(st.session_state.final_report_md, company_name)
    st.download_button("📄 Download Executive Report (PDF)", data=pdf_bytes, file_name=f"{company_name}_Report.pdf", mime="application/pdf")